[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Redirects for i18n
[[redirects]]
  from = "/"
  to = "/cs"
  status = 302

[[redirects]]
  from = "/sluzby"
  to = "/cs/sluzby"
  status = 301

[[redirects]]
  from = "/ai-skoleni"
  to = "/cs/sluzby/ai-skoleni"
  status = 301

[[redirects]]
  from = "/services"
  to = "/en/services"
  status = 301

[[redirects]]
  from = "/ai-training"
  to = "/en/services/ai-training"
  status = 301